package com.example.demo.mbg.mapper;

import com.example.demo.mbg.model.AcademicStudent;
import com.example.demo.mbg.model.AcademicStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcademicStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    long countByExample(AcademicStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int deleteByExample(AcademicStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int insert(AcademicStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int insertSelective(AcademicStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    List<AcademicStudent> selectByExample(AcademicStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    AcademicStudent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int updateByExampleSelective(@Param("record") AcademicStudent record, @Param("example") AcademicStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int updateByExample(@Param("record") AcademicStudent record, @Param("example") AcademicStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int updateByPrimaryKeySelective(AcademicStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int updateByPrimaryKey(AcademicStudent record);
}