package com.example.demo.mbg.mapper;

import com.example.demo.mbg.model.CourseStudent;
import com.example.demo.mbg.model.CourseStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    long countByExample(CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int deleteByExample(CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int insert(CourseStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int insertSelective(CourseStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    List<CourseStudent> selectByExample(CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    CourseStudent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByExampleSelective(@Param("record") CourseStudent record, @Param("example") CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByExample(@Param("record") CourseStudent record, @Param("example") CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByPrimaryKeySelective(CourseStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByPrimaryKey(CourseStudent record);
}