package com.example.demo.mbg.mapper;

import com.example.demo.mbg.model.Url;
import com.example.demo.mbg.model.UrlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    long countByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int deleteByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int insert(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int insertSelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    List<Url> selectByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    Url selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByExampleSelective(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByExample(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByPrimaryKeySelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByPrimaryKey(Url record);
}