package com.example.demo.mbg.mapper;

import com.example.demo.mbg.model.UserConfirmation;
import com.example.demo.mbg.model.UserConfirmationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserConfirmationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    long countByExample(UserConfirmationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int deleteByExample(UserConfirmationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int insert(UserConfirmation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int insertSelective(UserConfirmation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    List<UserConfirmation> selectByExample(UserConfirmationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    UserConfirmation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByExampleSelective(@Param("record") UserConfirmation record, @Param("example") UserConfirmationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByExample(@Param("record") UserConfirmation record, @Param("example") UserConfirmationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByPrimaryKeySelective(UserConfirmation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    int updateByPrimaryKey(UserConfirmation record);
}