package com.example.demo.mbg.mapper;

import com.example.demo.mbg.model.UserPossession;
import com.example.demo.mbg.model.UserPossessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPossessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    long countByExample(UserPossessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int deleteByExample(UserPossessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int insert(UserPossession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int insertSelective(UserPossession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    List<UserPossession> selectByExample(UserPossessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    UserPossession selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int updateByExampleSelective(@Param("record") UserPossession record, @Param("example") UserPossessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int updateByExample(@Param("record") UserPossession record, @Param("example") UserPossessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int updateByPrimaryKeySelective(UserPossession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    int updateByPrimaryKey(UserPossession record);
}