package com.example.demo.mbg.model;

import java.io.Serializable;

public class CourseStudent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.stu_id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private Long stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.course
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private String course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.credit
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.course_time
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private String courseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.id
     *
     * @return the value of course_student.id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.id
     *
     * @param id the value for course_student.id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.stu_id
     *
     * @return the value of course_student.stu_id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.stu_id
     *
     * @param stuId the value for course_student.stu_id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.course
     *
     * @return the value of course_student.course
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.course
     *
     * @param course the value for course_student.course
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setCourse(String course) {
        this.course = course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.credit
     *
     * @return the value of course_student.credit
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.credit
     *
     * @param credit the value for course_student.credit
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.course_time
     *
     * @return the value of course_student.course_time
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public String getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.course_time
     *
     * @param courseTime the value for course_student.course_time
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setCourseTime(String courseTime) {
        this.courseTime = courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stuId=").append(stuId);
        sb.append(", course=").append(course);
        sb.append(", credit=").append(credit);
        sb.append(", courseTime=").append(courseTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}