package com.example.demo.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Url implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.surl
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private String surl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.lurl
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private String lurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.views
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Integer views;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.create_time
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.id
     *
     * @return the value of url.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.id
     *
     * @param id the value for url.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.surl
     *
     * @return the value of url.surl
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getSurl() {
        return surl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.surl
     *
     * @param surl the value for url.surl
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setSurl(String surl) {
        this.surl = surl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.lurl
     *
     * @return the value of url.lurl
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getLurl() {
        return lurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.lurl
     *
     * @param lurl the value for url.lurl
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setLurl(String lurl) {
        this.lurl = lurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.views
     *
     * @return the value of url.views
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.views
     *
     * @param views the value for url.views
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.create_time
     *
     * @return the value of url.create_time
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.create_time
     *
     * @param createTime the value for url.create_time
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", surl=").append(surl);
        sb.append(", lurl=").append(lurl);
        sb.append(", views=").append(views);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}