package com.example.demo.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UrlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public UrlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSurlIsNull() {
            addCriterion("surl is null");
            return (Criteria) this;
        }

        public Criteria andSurlIsNotNull() {
            addCriterion("surl is not null");
            return (Criteria) this;
        }

        public Criteria andSurlEqualTo(String value) {
            addCriterion("surl =", value, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlNotEqualTo(String value) {
            addCriterion("surl <>", value, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlGreaterThan(String value) {
            addCriterion("surl >", value, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlGreaterThanOrEqualTo(String value) {
            addCriterion("surl >=", value, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlLessThan(String value) {
            addCriterion("surl <", value, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlLessThanOrEqualTo(String value) {
            addCriterion("surl <=", value, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlLike(String value) {
            addCriterion("surl like", value, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlNotLike(String value) {
            addCriterion("surl not like", value, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlIn(List<String> values) {
            addCriterion("surl in", values, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlNotIn(List<String> values) {
            addCriterion("surl not in", values, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlBetween(String value1, String value2) {
            addCriterion("surl between", value1, value2, "surl");
            return (Criteria) this;
        }

        public Criteria andSurlNotBetween(String value1, String value2) {
            addCriterion("surl not between", value1, value2, "surl");
            return (Criteria) this;
        }

        public Criteria andLurlIsNull() {
            addCriterion("lurl is null");
            return (Criteria) this;
        }

        public Criteria andLurlIsNotNull() {
            addCriterion("lurl is not null");
            return (Criteria) this;
        }

        public Criteria andLurlEqualTo(String value) {
            addCriterion("lurl =", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlNotEqualTo(String value) {
            addCriterion("lurl <>", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlGreaterThan(String value) {
            addCriterion("lurl >", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlGreaterThanOrEqualTo(String value) {
            addCriterion("lurl >=", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlLessThan(String value) {
            addCriterion("lurl <", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlLessThanOrEqualTo(String value) {
            addCriterion("lurl <=", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlLike(String value) {
            addCriterion("lurl like", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlNotLike(String value) {
            addCriterion("lurl not like", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlIn(List<String> values) {
            addCriterion("lurl in", values, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlNotIn(List<String> values) {
            addCriterion("lurl not in", values, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlBetween(String value1, String value2) {
            addCriterion("lurl between", value1, value2, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlNotBetween(String value1, String value2) {
            addCriterion("lurl not between", value1, value2, "lurl");
            return (Criteria) this;
        }

        public Criteria andViewsIsNull() {
            addCriterion("views is null");
            return (Criteria) this;
        }

        public Criteria andViewsIsNotNull() {
            addCriterion("views is not null");
            return (Criteria) this;
        }

        public Criteria andViewsEqualTo(Integer value) {
            addCriterion("views =", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotEqualTo(Integer value) {
            addCriterion("views <>", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsGreaterThan(Integer value) {
            addCriterion("views >", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsGreaterThanOrEqualTo(Integer value) {
            addCriterion("views >=", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsLessThan(Integer value) {
            addCriterion("views <", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsLessThanOrEqualTo(Integer value) {
            addCriterion("views <=", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsIn(List<Integer> values) {
            addCriterion("views in", values, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotIn(List<Integer> values) {
            addCriterion("views not in", values, "views");
            return (Criteria) this;
        }

        public Criteria andViewsBetween(Integer value1, Integer value2) {
            addCriterion("views between", value1, value2, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotBetween(Integer value1, Integer value2) {
            addCriterion("views not between", value1, value2, "views");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table url
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 20 14:18:41 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table url
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}