package com.example.demo.mbg.model;

import java.io.Serializable;

public class UserCheckin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_checkin.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_checkin.user_id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_checkin.sum
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Integer sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_checkin
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_checkin.id
     *
     * @return the value of user_checkin.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_checkin.id
     *
     * @param id the value for user_checkin.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_checkin.user_id
     *
     * @return the value of user_checkin.user_id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_checkin.user_id
     *
     * @param userId the value for user_checkin.user_id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_checkin.sum
     *
     * @return the value of user_checkin.sum
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_checkin.sum
     *
     * @param sum the value for user_checkin.sum
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_checkin
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", sum=").append(sum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}