package com.example.demo.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class UserLoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.ip_address
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.address
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.login_time
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.browser_type
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private String browserType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.operating_system
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private String operatingSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.platform
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_login_log
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.id
     *
     * @return the value of user_login_log.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.id
     *
     * @param id the value for user_login_log.id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_id
     *
     * @return the value of user_login_log.user_id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_id
     *
     * @param userId the value for user_login_log.user_id
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.ip_address
     *
     * @return the value of user_login_log.ip_address
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.ip_address
     *
     * @param ipAddress the value for user_login_log.ip_address
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.address
     *
     * @return the value of user_login_log.address
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.address
     *
     * @param address the value for user_login_log.address
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.login_time
     *
     * @return the value of user_login_log.login_time
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.login_time
     *
     * @param loginTime the value for user_login_log.login_time
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.browser_type
     *
     * @return the value of user_login_log.browser_type
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getBrowserType() {
        return browserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.browser_type
     *
     * @param browserType the value for user_login_log.browser_type
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setBrowserType(String browserType) {
        this.browserType = browserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.operating_system
     *
     * @return the value of user_login_log.operating_system
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.operating_system
     *
     * @param operatingSystem the value for user_login_log.operating_system
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.platform
     *
     * @return the value of user_login_log.platform
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.platform
     *
     * @param platform the value for user_login_log.platform
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append(", address=").append(address);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", browserType=").append(browserType);
        sb.append(", operatingSystem=").append(operatingSystem);
        sb.append(", platform=").append(platform);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}