package com.example.demo.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserConfirmationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public UserConfirmationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNull() {
            addCriterion("stu_id is null");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNotNull() {
            addCriterion("stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuIdEqualTo(Long value) {
            addCriterion("stu_id =", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotEqualTo(Long value) {
            addCriterion("stu_id <>", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThan(Long value) {
            addCriterion("stu_id >", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("stu_id >=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThan(Long value) {
            addCriterion("stu_id <", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThanOrEqualTo(Long value) {
            addCriterion("stu_id <=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdIn(List<Long> values) {
            addCriterion("stu_id in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotIn(List<Long> values) {
            addCriterion("stu_id not in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdBetween(Long value1, Long value2) {
            addCriterion("stu_id between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotBetween(Long value1, Long value2) {
            addCriterion("stu_id not between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationIsNull() {
            addCriterion("information_confirmation is null");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationIsNotNull() {
            addCriterion("information_confirmation is not null");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationEqualTo(Byte value) {
            addCriterion("information_confirmation =", value, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationNotEqualTo(Byte value) {
            addCriterion("information_confirmation <>", value, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationGreaterThan(Byte value) {
            addCriterion("information_confirmation >", value, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationGreaterThanOrEqualTo(Byte value) {
            addCriterion("information_confirmation >=", value, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationLessThan(Byte value) {
            addCriterion("information_confirmation <", value, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationLessThanOrEqualTo(Byte value) {
            addCriterion("information_confirmation <=", value, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationIn(List<Byte> values) {
            addCriterion("information_confirmation in", values, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationNotIn(List<Byte> values) {
            addCriterion("information_confirmation not in", values, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationBetween(Byte value1, Byte value2) {
            addCriterion("information_confirmation between", value1, value2, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationNotBetween(Byte value1, Byte value2) {
            addCriterion("information_confirmation not between", value1, value2, "informationConfirmation");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeIsNull() {
            addCriterion("information_confirmation_time is null");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeIsNotNull() {
            addCriterion("information_confirmation_time is not null");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeEqualTo(Date value) {
            addCriterion("information_confirmation_time =", value, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeNotEqualTo(Date value) {
            addCriterion("information_confirmation_time <>", value, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeGreaterThan(Date value) {
            addCriterion("information_confirmation_time >", value, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("information_confirmation_time >=", value, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeLessThan(Date value) {
            addCriterion("information_confirmation_time <", value, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeLessThanOrEqualTo(Date value) {
            addCriterion("information_confirmation_time <=", value, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeIn(List<Date> values) {
            addCriterion("information_confirmation_time in", values, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeNotIn(List<Date> values) {
            addCriterion("information_confirmation_time not in", values, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeBetween(Date value1, Date value2) {
            addCriterion("information_confirmation_time between", value1, value2, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andInformationConfirmationTimeNotBetween(Date value1, Date value2) {
            addCriterion("information_confirmation_time not between", value1, value2, "informationConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationIsNull() {
            addCriterion("course_confirmation is null");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationIsNotNull() {
            addCriterion("course_confirmation is not null");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationEqualTo(Byte value) {
            addCriterion("course_confirmation =", value, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationNotEqualTo(Byte value) {
            addCriterion("course_confirmation <>", value, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationGreaterThan(Byte value) {
            addCriterion("course_confirmation >", value, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationGreaterThanOrEqualTo(Byte value) {
            addCriterion("course_confirmation >=", value, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationLessThan(Byte value) {
            addCriterion("course_confirmation <", value, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationLessThanOrEqualTo(Byte value) {
            addCriterion("course_confirmation <=", value, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationIn(List<Byte> values) {
            addCriterion("course_confirmation in", values, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationNotIn(List<Byte> values) {
            addCriterion("course_confirmation not in", values, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationBetween(Byte value1, Byte value2) {
            addCriterion("course_confirmation between", value1, value2, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationNotBetween(Byte value1, Byte value2) {
            addCriterion("course_confirmation not between", value1, value2, "courseConfirmation");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeIsNull() {
            addCriterion("course_confirmation_time is null");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeIsNotNull() {
            addCriterion("course_confirmation_time is not null");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeEqualTo(Date value) {
            addCriterion("course_confirmation_time =", value, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeNotEqualTo(Date value) {
            addCriterion("course_confirmation_time <>", value, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeGreaterThan(Date value) {
            addCriterion("course_confirmation_time >", value, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("course_confirmation_time >=", value, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeLessThan(Date value) {
            addCriterion("course_confirmation_time <", value, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeLessThanOrEqualTo(Date value) {
            addCriterion("course_confirmation_time <=", value, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeIn(List<Date> values) {
            addCriterion("course_confirmation_time in", values, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeNotIn(List<Date> values) {
            addCriterion("course_confirmation_time not in", values, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeBetween(Date value1, Date value2) {
            addCriterion("course_confirmation_time between", value1, value2, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andCourseConfirmationTimeNotBetween(Date value1, Date value2) {
            addCriterion("course_confirmation_time not between", value1, value2, "courseConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationIsNull() {
            addCriterion("academic_confirmation is null");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationIsNotNull() {
            addCriterion("academic_confirmation is not null");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationEqualTo(Byte value) {
            addCriterion("academic_confirmation =", value, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationNotEqualTo(Byte value) {
            addCriterion("academic_confirmation <>", value, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationGreaterThan(Byte value) {
            addCriterion("academic_confirmation >", value, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationGreaterThanOrEqualTo(Byte value) {
            addCriterion("academic_confirmation >=", value, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationLessThan(Byte value) {
            addCriterion("academic_confirmation <", value, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationLessThanOrEqualTo(Byte value) {
            addCriterion("academic_confirmation <=", value, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationIn(List<Byte> values) {
            addCriterion("academic_confirmation in", values, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationNotIn(List<Byte> values) {
            addCriterion("academic_confirmation not in", values, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationBetween(Byte value1, Byte value2) {
            addCriterion("academic_confirmation between", value1, value2, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationNotBetween(Byte value1, Byte value2) {
            addCriterion("academic_confirmation not between", value1, value2, "academicConfirmation");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeIsNull() {
            addCriterion("academic_confirmation_time is null");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeIsNotNull() {
            addCriterion("academic_confirmation_time is not null");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeEqualTo(Date value) {
            addCriterion("academic_confirmation_time =", value, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeNotEqualTo(Date value) {
            addCriterion("academic_confirmation_time <>", value, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeGreaterThan(Date value) {
            addCriterion("academic_confirmation_time >", value, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("academic_confirmation_time >=", value, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeLessThan(Date value) {
            addCriterion("academic_confirmation_time <", value, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeLessThanOrEqualTo(Date value) {
            addCriterion("academic_confirmation_time <=", value, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeIn(List<Date> values) {
            addCriterion("academic_confirmation_time in", values, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeNotIn(List<Date> values) {
            addCriterion("academic_confirmation_time not in", values, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeBetween(Date value1, Date value2) {
            addCriterion("academic_confirmation_time between", value1, value2, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andAcademicConfirmationTimeNotBetween(Date value1, Date value2) {
            addCriterion("academic_confirmation_time not between", value1, value2, "academicConfirmationTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedIsNull() {
            addCriterion("dissertation_submitted is null");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedIsNotNull() {
            addCriterion("dissertation_submitted is not null");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedEqualTo(Byte value) {
            addCriterion("dissertation_submitted =", value, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedNotEqualTo(Byte value) {
            addCriterion("dissertation_submitted <>", value, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedGreaterThan(Byte value) {
            addCriterion("dissertation_submitted >", value, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedGreaterThanOrEqualTo(Byte value) {
            addCriterion("dissertation_submitted >=", value, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedLessThan(Byte value) {
            addCriterion("dissertation_submitted <", value, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedLessThanOrEqualTo(Byte value) {
            addCriterion("dissertation_submitted <=", value, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedIn(List<Byte> values) {
            addCriterion("dissertation_submitted in", values, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedNotIn(List<Byte> values) {
            addCriterion("dissertation_submitted not in", values, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedBetween(Byte value1, Byte value2) {
            addCriterion("dissertation_submitted between", value1, value2, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedNotBetween(Byte value1, Byte value2) {
            addCriterion("dissertation_submitted not between", value1, value2, "dissertationSubmitted");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeIsNull() {
            addCriterion("dissertation_submitted_time is null");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeIsNotNull() {
            addCriterion("dissertation_submitted_time is not null");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeEqualTo(Date value) {
            addCriterion("dissertation_submitted_time =", value, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeNotEqualTo(Date value) {
            addCriterion("dissertation_submitted_time <>", value, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeGreaterThan(Date value) {
            addCriterion("dissertation_submitted_time >", value, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("dissertation_submitted_time >=", value, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeLessThan(Date value) {
            addCriterion("dissertation_submitted_time <", value, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeLessThanOrEqualTo(Date value) {
            addCriterion("dissertation_submitted_time <=", value, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeIn(List<Date> values) {
            addCriterion("dissertation_submitted_time in", values, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeNotIn(List<Date> values) {
            addCriterion("dissertation_submitted_time not in", values, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeBetween(Date value1, Date value2) {
            addCriterion("dissertation_submitted_time between", value1, value2, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationSubmittedTimeNotBetween(Date value1, Date value2) {
            addCriterion("dissertation_submitted_time not between", value1, value2, "dissertationSubmittedTime");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleIsNull() {
            addCriterion("dissertation_title is null");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleIsNotNull() {
            addCriterion("dissertation_title is not null");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleEqualTo(String value) {
            addCriterion("dissertation_title =", value, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleNotEqualTo(String value) {
            addCriterion("dissertation_title <>", value, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleGreaterThan(String value) {
            addCriterion("dissertation_title >", value, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleGreaterThanOrEqualTo(String value) {
            addCriterion("dissertation_title >=", value, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleLessThan(String value) {
            addCriterion("dissertation_title <", value, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleLessThanOrEqualTo(String value) {
            addCriterion("dissertation_title <=", value, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleLike(String value) {
            addCriterion("dissertation_title like", value, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleNotLike(String value) {
            addCriterion("dissertation_title not like", value, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleIn(List<String> values) {
            addCriterion("dissertation_title in", values, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleNotIn(List<String> values) {
            addCriterion("dissertation_title not in", values, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleBetween(String value1, String value2) {
            addCriterion("dissertation_title between", value1, value2, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationTitleNotBetween(String value1, String value2) {
            addCriterion("dissertation_title not between", value1, value2, "dissertationTitle");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsIsNull() {
            addCriterion("dissertation_keywords is null");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsIsNotNull() {
            addCriterion("dissertation_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsEqualTo(String value) {
            addCriterion("dissertation_keywords =", value, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsNotEqualTo(String value) {
            addCriterion("dissertation_keywords <>", value, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsGreaterThan(String value) {
            addCriterion("dissertation_keywords >", value, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("dissertation_keywords >=", value, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsLessThan(String value) {
            addCriterion("dissertation_keywords <", value, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsLessThanOrEqualTo(String value) {
            addCriterion("dissertation_keywords <=", value, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsLike(String value) {
            addCriterion("dissertation_keywords like", value, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsNotLike(String value) {
            addCriterion("dissertation_keywords not like", value, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsIn(List<String> values) {
            addCriterion("dissertation_keywords in", values, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsNotIn(List<String> values) {
            addCriterion("dissertation_keywords not in", values, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsBetween(String value1, String value2) {
            addCriterion("dissertation_keywords between", value1, value2, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationKeywordsNotBetween(String value1, String value2) {
            addCriterion("dissertation_keywords not between", value1, value2, "dissertationKeywords");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractIsNull() {
            addCriterion("dissertation_abstract is null");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractIsNotNull() {
            addCriterion("dissertation_abstract is not null");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractEqualTo(String value) {
            addCriterion("dissertation_abstract =", value, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractNotEqualTo(String value) {
            addCriterion("dissertation_abstract <>", value, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractGreaterThan(String value) {
            addCriterion("dissertation_abstract >", value, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractGreaterThanOrEqualTo(String value) {
            addCriterion("dissertation_abstract >=", value, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractLessThan(String value) {
            addCriterion("dissertation_abstract <", value, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractLessThanOrEqualTo(String value) {
            addCriterion("dissertation_abstract <=", value, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractLike(String value) {
            addCriterion("dissertation_abstract like", value, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractNotLike(String value) {
            addCriterion("dissertation_abstract not like", value, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractIn(List<String> values) {
            addCriterion("dissertation_abstract in", values, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractNotIn(List<String> values) {
            addCriterion("dissertation_abstract not in", values, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractBetween(String value1, String value2) {
            addCriterion("dissertation_abstract between", value1, value2, "dissertationAbstract");
            return (Criteria) this;
        }

        public Criteria andDissertationAbstractNotBetween(String value1, String value2) {
            addCriterion("dissertation_abstract not between", value1, value2, "dissertationAbstract");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_confirmation
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 20 14:18:41 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_confirmation
     *
     * @mbg.generated Sun Aug 20 14:18:41 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}