package com.example.demo.mbg.model;

import java.io.Serializable;

public class UserPossession implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_possession.id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_possession.user_id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_possession.money
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private Long money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_possession.checkin_count
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private Integer checkinCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_possession.id
     *
     * @return the value of user_possession.id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_possession.id
     *
     * @param id the value for user_possession.id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_possession.user_id
     *
     * @return the value of user_possession.user_id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_possession.user_id
     *
     * @param userId the value for user_possession.user_id
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_possession.money
     *
     * @return the value of user_possession.money
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_possession.money
     *
     * @param money the value for user_possession.money
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_possession.checkin_count
     *
     * @return the value of user_possession.checkin_count
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public Integer getCheckinCount() {
        return checkinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_possession.checkin_count
     *
     * @param checkinCount the value for user_possession.checkin_count
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    public void setCheckinCount(Integer checkinCount) {
        this.checkinCount = checkinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_possession
     *
     * @mbg.generated Sat Jul 22 20:32:02 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", money=").append(money);
        sb.append(", checkinCount=").append(checkinCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}